camunda.bpm:
  job-execution.enabled: false
  id-generator: simple
  generic-properties:
    message-trowing: true

spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/dev?useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8082